# # from fastapi import FastAPI, UploadFile, File, Form
# # from fastapi.middleware.cors import CORSMiddleware
# # from fastapi.responses import JSONResponse
# # from typing import List
# # import json

# # app = FastAPI(title="CodeLoomers Backend")

# # app.add_middleware(
# #     CORSMiddleware,
# #     allow_origins=["http://localhost:8501", "*"],
# #     allow_credentials=True,
# #     allow_methods=["*"],
# #     allow_headers=["*"],
# # )

# # # Mock Gemini/Speech responses (replace with real APIs later)
# # mock_profiles = []

# # @app.get("/")
# # def root():
# #     return {"message": "CodeLoomers Backend Ready"}

# # @app.post("/artisan/generate")
# # async def generate_listings(story: str = Form(...), photo_count: int = Form(0)):
# #     """PPT: Generate after story+photos"""
# #     profile = {
# #         "title_en": "Handwoven Silk Saree - Karnataka Artisan",
# #         "title_hi": "हाथ से बुना सिल्क साड़ी",
# #         "caption_en": "Woven with love by Savita's family for 3 generations.",
# #         "caption_hi": "साविता के परिवार ने 3 पीढ़ियों से प्यार से बुना।",
# #         "story": story or "My family crafts beautiful sarees.",
# #         "photos": photo_count
# #     }
# #     mock_profiles.append(profile)
# #     return profile

# # @app.get("/buyer/search")
# # async def search(q: str):
# #     """PPT: Buyer search + rerank"""
# #     results = [p for p in mock_profiles if q.lower() in p["story"].lower()]
# #     return {"results": results[:3]}

# # @app.post("/artisan/audio")
# # async def audio_upload(audio_bytes: bytes = File(...)):
# #     """Mock Speech-to-Text"""
# #     return {"story_text": "Transcribed: I make beautiful sarees in my village."}


# # from fastapi import FastAPI, UploadFile, File, Form
# # from fastapi.middleware.cors import CORSMiddleware
# # import vertexai
# # from vertexai.generative_models import GenerativeModel
# # from google.cloud import firestore, storage, speech_v1p1beta1 as speech
# # import os

# # app = FastAPI()
# # app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# # # GCP Setup (uses your serviceAccountKey.json)
# # os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "serviceAccountKey.json"
# # vertexai.init(project="codloomers-prod", location="us-central1")
# # model = GenerativeModel("gemini-1.5-flash")
# # db = firestore.Client()
# # bucket = storage.Client().bucket("codloomers-photos")
# # speech_client = speech.SpeechClient()

# # @app.get("/")
# # def root():
# #     return {"status": "GCP Backend Ready - Gemini + Firestore"}

# # @app.post("/artisan/generate")
# # async def generate(story: str = Form(...)):
# #     # REAL GEMINI API
# #     response = model.generate_content(f"Create beautiful product title and caption for artisan story: {story}")
# #     title = response.text[:100]
    
# #     # REAL FIRESTORE
# #     profile = {"story": story, "title_en": title, "created": firestore.SERVER_TIMESTAMP}
# #     db.collection("artisans").add(profile)
    
# #     return {
# #         "title_en": title,
# #         "title_hi": "हाथ से बुना सिल्क साड़ी",  # Mock Hindi for demo
# #         "caption_en": "Generated by Gemini AI",
# #         "story": story
# #     }

# # @app.get("/buyer/search")
# # async def search(q: str):
# #     # REAL FIRESTORE SEARCH
# #     artisans = db.collection("artisans").limit(10).stream()
# #     results = [{"title_en": a.to_dict().get("title_en", "Artisan"), "story": a.to_dict().get("story", "")} 
# #                for a in artisans if q.lower() in a.to_dict().get("story", "").lower()]
# #     return {"results": results}
# # @app.get("/seed-data")
# # def seed_demo():
# #     """Add 3 demo artisans for buyer search"""
# #     demos = [
# #         {"story": "Karnataka silk sarees, 3 generations family", "title_en": "Handwoven Silk Saree"},
# #         {"story": "Mysore paintings on silk", "title_en": "Traditional Mysore Painting"}, 
# #         {"story": "Coorg bamboo crafts", "title_en": "Handcrafted Bamboo Basket"}
# #     ]
# #     for demo in demos:
# #         db.collection("artisans").add(demo)
# #     return {"added": 3}



# from fastapi import FastAPI, Form
# from fastapi.middleware.cors import CORSMiddleware  # Fixed import
# import os
# from google.cloud import firestore
# import google.auth

# # Service account (auto-detects serviceAccountKey.json)
# os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "serviceAccountKey.json"

# app = FastAPI(title="CodeLoomers Backend")

# # CORS Fixed - proper parameters
# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"],  # Fixed: list format
#     allow_credentials=True,
#     allow_methods=["*"],  # Fixed: list format
#     allow_headers=["*"],  # Fixed: list format
# )

# # Initialize GCP (with fallback)
# model = None
# db = None

# try:
#     # Firestore only (simpler, works 100%)
#     db = firestore.Client()
#     print("✅ Firestore Connected!")
    
#     # Test Firestore
#     db.collection("test").document("ping").set({"status": "ok"})
#     print("✅ Firestore Test OK!")
    
# except Exception as e:
#     print(f"⚠️ Firestore Error: {e}")

# @app.get("/")
# def root():
#     return {"status": "CodeLoomers Backend - Firestore Ready"}

# @app.post("/artisan/generate")
# async def generate(story: str = Form(...)):
#     title = f"Handwoven Artisan Craft: {story[:50]}"  # Mock Gemini for stability
    
#     if db:
#         # REAL FIRESTORE SAVE
#         profile = {
#             "story": story, 
#             "title_en": title,
#             "created": firestore.SERVER_TIMESTAMP
#         }
#         db.collection("artisans").add(profile)
#         print(f"✅ Saved artisan to Firestore: {title}")
    
#     return {
#         "title_en": title,
#         "title_hi": "हाथ से बुना शिल्प",
#         "caption_en": "Crafted with tradition by local artisans", 
#         "story": story
#     }

# @app.get("/buyer/search")
# async def search(q: str):
#     if db:
#         # REAL FIRESTORE SEARCH
#         artisans = db.collection("artisans").limit(5).stream()
#         results = []
#         for artisan in artisans:
#             data = artisan.to_dict()
#             if q.lower() in data.get("story", "").lower():
#                 results.append({
#                     "title_en": data.get("title_en", "Artisan Craft"),
#                     "story": data.get("story", "")
#                 })
#     else:
#         results = []
    
#     return {"results": results}

from fastapi import FastAPI, Form
from typing import Dict
from google.cloud import firestore
from app.config import db
from fastapi import UploadFile, File
from app.speech import transcribe

app = FastAPI(
    title="CodeLoomers Backend",
    version="0.1.0"
)

@app.get("/", response_model=Dict[str, str])
def root():
    return {"status": "Backend running"}

@app.post("/artisan/generate", response_model=Dict[str, str])
def generate_artisan(story: str = Form(...)):
    title = f"Handwoven Craft: {story[:40]}"

    db.collection("artisans").add({
        "story": story,
        "title_en": title,
        "created": firestore.SERVER_TIMESTAMP
    })

    return {
        "title_en": title,
        "caption_en": "Crafted with tradition by local artisans",
        "story": story
    }
@app.post("/artisan/voice")
async def upload_voice(audio: UploadFile = File(...)):
    """
    Receives an audio file and returns transcribed text
    """

    audio_bytes = await audio.read()

    text = transcribe(audio_bytes)

    return {
        "transcription": text
    }
# from fastapi import UploadFile, File
# from app.vision import analyze_image

# @app.post("/artisan/image")
# async def upload_image(image: UploadFile = File(...)):
#     image_bytes = await image.read()

#     result = analyze_image(image_bytes)

#     return {
#         "labels": result["labels"],
#         "objects": result["objects"],
#         "description": result["description"]
#     }
from fastapi import UploadFile, File
from app.vision import analyze_image
print(">>> IMAGE ROUTE LOADED <<<")

# @app.post("/artisan/image")
# async def upload_image(image: UploadFile = File(...)):
#     image_bytes = await image.read()
#     result = analyze_image(image_bytes)
#     return result
# from app.gemini import generate_craft_twin

@app.post("/artisan/image")
async def analyze_artisan_image(image: UploadFile = File(...)):
    vision_result = analyze_image(image)

    labels = vision_result["labels"]
    objects = vision_result["objects"]

    # NEW: Generate story
    story = generate_story_from_image(labels, objects)

    # Reuse your existing generator logic
    generated = generate_artisan_content(story)

    return {
        "labels": labels,
        "objects": objects,
        "story": story,
        "title_en": generated["title_en"],
        "caption_en": generated["caption_en"]
    }

@app.post("/artisan/generate-ai")
def generate_ai_content(
    story: str = Form(...),
    labels: str = Form(...)
):
    labels_list = [l.strip() for l in labels.split(",")]

    result = generate_craft_twin(story, labels_list)
    return result
from app.artisan_story import generate_story_from_image
